# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        'node 10.x':
          nodeVersion: '10.x'
        'node 12.x':
          nodeVersion: '12.x'
    steps:
      - template: templates/build-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)

  - job: MacOS
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        'node 10.x':
          nodeVersion: '10.x'
        'node 12.x':
          nodeVersion: '12.x'
    steps:
      - template: templates/build-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)
          runTests: 'false' # There is no Chrome installed on MacOS


  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        'node 10.x':
          nodeVersion: '10.x'
        'node 12.x':
          nodeVersion: '12.x'
    steps:
      - template: templates/build-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)
