# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: templates/build-steps.yml

  - job: MacOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: templates/build-steps.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: templates/build-steps.yml
