# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

strategy:
  matrix:
    node_10_x:
      nodeVersion: '10.x'
    node_12_x:
      nodeVersion: '12.x'

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: templates/build-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)

# There is no Chrome installed on MacOS
#  - job: MacOS
#    pool:
#      vmImage: 'macOS-10.14'
#    steps:
#      - template: templates/build-steps.yml

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: templates/build-steps.yml
        parameters:
          nodeVersion: $(nodeVersion)
